/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sdk_JNIClassB */

#ifndef _Included_sdk_JNIClassB
#define _Included_sdk_JNIClassB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sdk_JNIClassB
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sdk_JNIClassB_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     sdk_JNIClassB
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_sdk_JNIClassB_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sdk_JNIClassB
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sdk_JNIClassB_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sdk_JNIClassB
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_sdk_JNIClassB_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
