/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sdk_JNIClassA */

#ifndef _Included_sdk_JNIClassA
#define _Included_sdk_JNIClassA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sdk_JNIClassA
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sdk_JNIClassA_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     sdk_JNIClassA
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_sdk_JNIClassA_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sdk_JNIClassA
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sdk_JNIClassA_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sdk_JNIClassA
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_sdk_JNIClassA_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
